Repository JNU-econovation/BuddyBridge_BE, pull requests merged in 2024-11, with the labels that each got.

#187 [FIX] 봉사 시각 LocalDateTime에서 LocalTime으로 변경
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
  src/main/java/econo/buddybridge/post/dto/PostResDto.java
  src/main/java/econo/buddybridge/post/dto/PostUpdateReqDto.java
  src/main/java/econo/buddybridge/post/entity/AssistanceTime.java
Labels: bug, enhancement

#189 [FEAT] 게시글 작성을 위한 열거형 정보를 제공하는 엔드포인트 구현
  src/main/java/econo/buddybridge/post/controller/PostController.java
  src/main/java/econo/buddybridge/post/dto/PostEnumResDto.java
  src/main/java/econo/buddybridge/post/dto/PostResDto.java
  src/main/java/econo/buddybridge/post/service/PostService.java
Labels: enhancement

#190 [FEAT] JWT 설정 및 적용
  build.gradle
  src/main/java/econo/buddybridge/BuddyBridgeApplication.java
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/controller/AuthTestController.java
  src/main/java/econo/buddybridge/auth/jwt/AuthToken.java
  src/main/java/econo/buddybridge/auth/jwt/RefreshToken.java
  src/main/java/econo/buddybridge/auth/jwt/TokenType.java
  src/main/java/econo/buddybridge/auth/jwt/exception/ExpiredTokenException.java
  src/main/java/econo/buddybridge/auth/jwt/exception/InvalidAccessTokenException.java
  src/main/java/econo/buddybridge/auth/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/econo/buddybridge/auth/jwt/exception/JwtErrorCode.java
  src/main/java/econo/buddybridge/auth/jwt/exception/MissingTokenException.java
  src/main/java/econo/buddybridge/auth/jwt/repository/TokenRepository.java
  src/main/java/econo/buddybridge/auth/jwt/service/AuthTokenService.java
  src/main/java/econo/buddybridge/auth/jwt/service/JwtTokenProvider.java
  src/main/java/econo/buddybridge/auth/resolver/MemberToken.java
  src/main/java/econo/buddybridge/auth/resolver/MemberTokenResolver.java
  src/main/java/econo/buddybridge/auth/service/OAuthLoginService.java
  src/main/java/econo/buddybridge/config/JPAConfig.java
  src/main/java/econo/buddybridge/config/JwtInterceptor.java
  src/main/java/econo/buddybridge/config/RedisConfig.java
  src/main/java/econo/buddybridge/config/WebConfig.java
  src/main/java/econo/buddybridge/member/dto/MemberResDto.java
  src/main/resources/application.yml
  src/test/java/econo/buddybridge/auth/jwt/repository/TokenRepositoryTest.java
Labels: enhancement

#195 [FEAT] 로그인 기능 구현
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/dto/LoginReqDto.java
  src/main/java/econo/buddybridge/auth/service/AuthService.java
  src/main/java/econo/buddybridge/auth/utils/PasswordEncoder.java
  src/main/java/econo/buddybridge/member/exception/InvalidPasswordException.java
  src/main/java/econo/buddybridge/member/exception/MemberErrorCode.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
Labels: enhancement

#199 [DOCS] Swagger JWT SecurityScheme 추가
  src/main/java/econo/buddybridge/config/SwaggerConfig.java
Labels: documentation

#201 [FEAT] 닉네임 필드 추가 입력 및 중복 확인 api 구현
  src/main/java/econo/buddybridge/member/controller/DuplicationCheckController.java
  src/main/java/econo/buddybridge/member/dto/EmailReqDto.java
  src/main/java/econo/buddybridge/member/dto/MemberSignUpReqDto.java
  src/main/java/econo/buddybridge/member/dto/NicknameReqDto.java
  src/main/java/econo/buddybridge/member/exception/InvalidPasswordException.java
  src/main/java/econo/buddybridge/member/exception/InvalidPasswordOrEmailException.java
  src/main/java/econo/buddybridge/member/exception/MemberErrorCode.java
  src/main/java/econo/buddybridge/member/exception/MemberNicknameAlreadyExistsException.java
  src/main/java/econo/buddybridge/member/repository/MemberRepository.java
  src/main/java/econo/buddybridge/member/service/DuplicationCheckService.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
Labels: enhancement

#203 [DOCS] MemberToken 주입 데이터 Swagger에서 안보이게 수정
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/controller/OAuthController.java
  src/main/java/econo/buddybridge/common/exception/GlobalExceptionHandler.java
Labels: documentation

#207 [DOCS] Swagger 커스텀 - 예외처리 응답 설정 추가
  src/main/java/econo/buddybridge/auth/exception/AlreadyLogoutException.java
  src/main/java/econo/buddybridge/auth/exception/EncryptFailedException.java
  src/main/java/econo/buddybridge/auth/exception/FeignKakaoException.java
  src/main/java/econo/buddybridge/auth/exception/FeignRedirectException.java
  src/main/java/econo/buddybridge/auth/exception/GenerateSaltFailedException.java
  src/main/java/econo/buddybridge/auth/exception/SessionAlreadyExistsException.java
  src/main/java/econo/buddybridge/chat/chatmessage/exception/LastChatMessageNotFoundException.java
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/comment/exception/CommentDeleteNotAllowedException.java
  src/main/java/econo/buddybridge/comment/exception/CommentInvalidDirectionException.java
  src/main/java/econo/buddybridge/comment/exception/CommentNotFoundException.java
  src/main/java/econo/buddybridge/comment/exception/CommentUpdateNotAllowedException.java
  src/main/java/econo/buddybridge/common/docs/comment/CreateCommentExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/comment/DeleteCommentExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/comment/GetCommentExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/comment/UpdateCommentExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/notification/BatchUpdateNotificationExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/notification/GetNotificationExceptionDocs.java
  src/main/java/econo/buddybridge/common/docs/notification/UpdateNotificationExceptionDocs.java
  src/main/java/econo/buddybridge/common/swagger/ApiExceptionExamples.java
  src/main/java/econo/buddybridge/common/swagger/ExceptionDoc.java
  src/main/java/econo/buddybridge/common/swagger/ExplainError.java
  src/main/java/econo/buddybridge/common/swagger/SwaggerExampleHolder.java
  src/main/java/econo/buddybridge/common/swagger/SwaggerExceptionDoc.java
  src/main/java/econo/buddybridge/config/SwaggerConfig.java
  src/main/java/econo/buddybridge/matching/exception/MatchingCompletedException.java
  src/main/java/econo/buddybridge/matching/exception/MatchingNotFoundException.java
  src/main/java/econo/buddybridge/matching/exception/MatchingUnauthorizedAccessException.java
  src/main/java/econo/buddybridge/member/exception/InvalidPasswordOrEmailException.java
  src/main/java/econo/buddybridge/member/exception/MemberEmailAlreadyExistsException.java
  src/main/java/econo/buddybridge/member/exception/MemberNicknameAlreadyExistsException.java
  src/main/java/econo/buddybridge/member/exception/MemberNotFoundException.java
  src/main/java/econo/buddybridge/notification/controller/NotificationController.java
  src/main/java/econo/buddybridge/notification/exception/NotificationAccessDeniedException.java
  src/main/java/econo/buddybridge/notification/exception/NotificationNotFoundException.java
  src/main/java/econo/buddybridge/post/exception/PostDeleteNotAllowedException.java
  src/main/java/econo/buddybridge/post/exception/PostInvalidSortValueException.java
  src/main/java/econo/buddybridge/post/exception/PostNotFoundException.java
  src/main/java/econo/buddybridge/post/exception/PostUnauthorizedAccessException.java
  src/main/java/econo/buddybridge/post/exception/PostUpdateNotAllowedException.java
  src/main/java/econo/buddybridge/utils/api/ApiResponse.java
Labels: documentation, enhancement

#215 [REFACTOR] 카카오 소셜 로그인 방식 JWT로 변경
  src/main/java/econo/buddybridge/auth/controller/OAuthController.java
Labels: enhancement

#213 [REFACTOR] 게시글 작성 시 요청한 회원의 정보로 작성자 정보 저장
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
Labels: enhancement

#211 [REFACTOR] 회원 정보 수정 범위를 닉네임과 장애유형으로 제한
  src/main/java/econo/buddybridge/member/dto/MemberReqDto.java
  src/main/java/econo/buddybridge/member/entity/Member.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
Labels: enhancement

#219 [FIX] 카카오 소셜로그인 Redirect시 토큰을 쿼리파라미터로 전달하도록 수정
  src/main/java/econo/buddybridge/auth/controller/OAuthController.java
Labels: bug

#217 [FEAT] 성별이 다를 경우 댓글 생성 제한
  src/main/java/econo/buddybridge/comment/exception/CommentErrorCode.java
  src/main/java/econo/buddybridge/comment/exception/CommentSameGenderOnlyException.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
Labels: enhancement

#221 [FEAT] 로그아웃 기능 구현
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/jwt/exception/JwtErrorCode.java
  src/main/java/econo/buddybridge/auth/jwt/exception/LoggedOutTokenException.java
  src/main/java/econo/buddybridge/auth/jwt/service/AuthTokenService.java
  src/main/java/econo/buddybridge/auth/jwt/service/JwtTokenProvider.java
  src/main/java/econo/buddybridge/auth/service/AuthService.java
  src/main/java/econo/buddybridge/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/econo/buddybridge/config/JwtInterceptor.java
Labels: enhancement
