Repository JNU-econovation/BuddyBridge_BE, pull requests merged in 2024-09, with the labels that each got.

#126 [FIX] Exception 생성자 private로 변경
  src/main/java/econo/buddybridge/chat/chatmessage/exception/LastChatMessageNotFoundException.java
  src/main/java/econo/buddybridge/matching/exception/MatchingUnauthorizedAccessException.java
  src/main/java/econo/buddybridge/notification/exception/NotificationAccessDeniedException.java
  src/main/java/econo/buddybridge/notification/exception/NotificationNotFoundException.java
  src/main/java/econo/buddybridge/post/exception/PostDeleteNotAllowedException.java
  src/main/java/econo/buddybridge/post/exception/PostErrorCode.java
Labels: invalid

#130 [FEAT] Swagger 적용
  build.gradle
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/config/SwaggerConfig.java
  src/main/java/econo/buddybridge/config/WebConfig.java
  src/main/java/econo/buddybridge/matching/controller/MatchingController.java
  src/main/java/econo/buddybridge/matching/controller/MatchingRoomController.java
  src/main/java/econo/buddybridge/member/controller/MemberController.java
  src/main/java/econo/buddybridge/notification/controller/EmitterController.java
  src/main/java/econo/buddybridge/notification/controller/NotificationController.java
  src/main/java/econo/buddybridge/post/controller/PostController.java
Labels: enhancement

#132 [FEAT] MyPage 본인이 작성한 게시글 및 댓글 조회, docker volume 설정
  docker-compose.yml
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/comment/dto/MyPageCommentCustomPage.java
  src/main/java/econo/buddybridge/comment/dto/MyPageCommentResDto.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepositoryCustom.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepositoryImpl.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/matching/controller/MatchingRoomController.java
  src/main/java/econo/buddybridge/post/controller/PostController.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
  src/main/java/econo/buddybridge/post/service/PostService.java
  src/main/resources/application.yml
Labels: enhancement

#136 [FIX]: 게시글 DisabilityType 직접 받아오기, 게시글 필터링 시 게시글의 DisabilityType 활용
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
Labels: bug

#137 [FEAT] 테스트 로그인 재구현
  Dockerfile
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/exception/AuthErrorCode.java
  src/main/java/econo/buddybridge/auth/exception/SessionAlreadyExistsException.java
  src/main/java/econo/buddybridge/config/WebConfig.java
  src/main/java/econo/buddybridge/utils/p6spy/P6SpyConfig.java
  src/main/java/econo/buddybridge/utils/p6spy/P6SpyEventListener.java
  src/main/resources/application.yml
Labels: enhancement

#139 [FEAT] 운영 환경에 따라 개발용 로직 비활성화
  src/main/java/econo/buddybridge/auth/controller/AuthController.java
  src/main/java/econo/buddybridge/auth/controller/AuthTestController.java
Labels: enhancement

#141 [REFACTOR] FeignClient 예외처리 클래스 비즈니스 예외로 전환
  src/main/java/econo/buddybridge/auth/exception/AuthErrorCode.java
  src/main/java/econo/buddybridge/auth/exception/FeignKakaoException.java
  src/main/java/econo/buddybridge/auth/exception/FeignRedirectException.java
  src/main/java/econo/buddybridge/auth/exception/KakaoApiException.java
  src/main/java/econo/buddybridge/auth/exception/RedirectException.java
  src/main/java/econo/buddybridge/config/OpenFeignConfig.java
  src/main/java/econo/buddybridge/config/SwaggerConfig.java
Labels: enhancement

#143 [FEAT] 게시글 찜하기 기능 구현, Mypage 찜한 게시글 목록 조회
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/post/controller/PostLikeController.java
  src/main/java/econo/buddybridge/post/entity/PostLike.java
  src/main/java/econo/buddybridge/post/exception/PostErrorCode.java
  src/main/java/econo/buddybridge/post/exception/PostInvalidSortValueException.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepository.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepositoryCustomImpl.java
  src/main/java/econo/buddybridge/post/repository/PostRepository.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
  src/main/java/econo/buddybridge/post/service/PostLikeService.java
Labels: enhancement

#145 [CHORE] 운영 서버 workflow 작성 및 개발 서버 workflow 파일 이름 변경
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: enhancement

#147 [CHORE] 운영 서버 workflow 작성 및 개발 서버 workflow 파일 이름 변경 (#145)
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: enhancement

#155 [FEAT] 알림 전체 읽기
  src/main/java/econo/buddybridge/config/OpenFeignConfig.java
  src/main/java/econo/buddybridge/config/WebConfig.java
  src/main/java/econo/buddybridge/notification/controller/NotificationController.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepository.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepositoryCustom.java
  src/main/java/econo/buddybridge/notification/service/NotificationService.java
  src/main/java/econo/buddybridge/post/controller/PostLikeController.java
Labels: enhancement

#158 [FEAT] 게시글 조회시 사용자가 찜한 게시글인지 확인 가능한 값 추가
  src/main/java/econo/buddybridge/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/econo/buddybridge/post/controller/PostController.java
  src/main/java/econo/buddybridge/post/dto/PostResDto.java
  src/main/java/econo/buddybridge/post/entity/Post.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepositoryCustomImpl.java
  src/main/java/econo/buddybridge/post/repository/PostRepository.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
  src/main/java/econo/buddybridge/post/service/PostService.java
  src/main/java/econo/buddybridge/utils/session/SessionUtils.java
Labels: enhancement

#162 [FEAT] 알림 조회 시 읽음 여부 필터링
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepositoryCustom.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepositoryImpl.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/matching/entity/Matching.java
  src/main/java/econo/buddybridge/notification/controller/NotificationController.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepositoryCustom.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepositoryImpl.java
  src/main/java/econo/buddybridge/notification/service/NotificationService.java
Labels: enhancement

#167 [FEAT]: 장애유형 다중 필터링 적용
  src/main/java/econo/buddybridge/post/controller/PostController.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
  src/main/java/econo/buddybridge/post/service/PostService.java
Labels: enhancement

#169 [REFACTOR] 채팅 목록 조회 로직 개선
  src/main/java/econo/buddybridge/chat/chatmessage/dto/ChatMessageCustomPage.java
  src/main/java/econo/buddybridge/chat/chatmessage/dto/ChatMessageReqDto.java
  src/main/java/econo/buddybridge/chat/chatmessage/dto/ChatMessageResDto.java
  src/main/java/econo/buddybridge/chat/chatmessage/dto/ChatMessagesWithCursor.java
  src/main/java/econo/buddybridge/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/econo/buddybridge/chat/chatmessage/repository/ChatMessageRepositoryCustom.java
  src/main/java/econo/buddybridge/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/econo/buddybridge/matching/dto/ReceiverDto.java
  src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
  src/main/java/econo/buddybridge/matching/service/MatchingRoomService.java
  src/main/java/econo/buddybridge/matching/service/MatchingService.java
Labels: bug, enhancement

#171 [FEAT] 사용자 정보에 카카오 토큰 저장
  src/main/java/econo/buddybridge/auth/dto/kakao/KakaoErrorResponse.java
  src/main/java/econo/buddybridge/auth/dto/kakao/KakaoInfoResponse.java
  src/main/java/econo/buddybridge/auth/dto/kakao/KakaoTokens.java
  src/main/java/econo/buddybridge/auth/dto/kakao/UserInfoWithKakaoToken.java
  src/main/java/econo/buddybridge/auth/service/OAuthInfoService.java
  src/main/java/econo/buddybridge/auth/service/OAuthLoginService.java
  src/main/java/econo/buddybridge/member/entity/Member.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
Labels: enhancement

#173 [FEAT] 조회 가능한 알림은 3일 이내로 제한
  src/main/java/econo/buddybridge/auth/exception/AlreadyLogoutException.java
  src/main/java/econo/buddybridge/auth/service/OAuthLoginService.java
  src/main/java/econo/buddybridge/chat/chatmessage/exception/LastChatMessageNotFoundException.java
  src/main/java/econo/buddybridge/comment/dto/CommentCustomPage.java
  src/main/java/econo/buddybridge/comment/dto/CommentReqDto.java
  src/main/java/econo/buddybridge/comment/dto/MyPageCommentCustomPage.java
  src/main/java/econo/buddybridge/comment/dto/MyPageCommentResDto.java
  src/main/java/econo/buddybridge/comment/exception/CommentDeleteNotAllowedException.java
  src/main/java/econo/buddybridge/comment/exception/CommentInvalidDirectionException.java
  src/main/java/econo/buddybridge/common/annotation/AllowAnonymous.java
  src/main/java/econo/buddybridge/common/exception/GlobalExceptionHandler.java
  src/main/java/econo/buddybridge/common/exception/ValidationError.java
  src/main/java/econo/buddybridge/matching/controller/MatchingRoomController.java
  src/main/java/econo/buddybridge/matching/dto/MatchingCustomPage.java
  src/main/java/econo/buddybridge/matching/dto/MatchingReqDto.java
  src/main/java/econo/buddybridge/matching/dto/MatchingResDto.java
  src/main/java/econo/buddybridge/matching/dto/MatchingUpdateDto.java
  src/main/java/econo/buddybridge/matching/entity/Matching.java
  src/main/java/econo/buddybridge/matching/entity/MatchingStatus.java
  src/main/java/econo/buddybridge/matching/exception/MatchingNotFoundException.java
  src/main/java/econo/buddybridge/matching/exception/MatchingUnauthorizedAccessException.java
  src/main/java/econo/buddybridge/matching/repository/MatchingRepositoryCustom.java
  src/main/java/econo/buddybridge/matching/service/MatchingService.java
  src/main/java/econo/buddybridge/member/exception/MemberNotFoundException.java
  src/main/java/econo/buddybridge/notification/controller/EmitterController.java
  src/main/java/econo/buddybridge/notification/dto/NotificationCustomPage.java
  src/main/java/econo/buddybridge/notification/dto/NotificationResDto.java
  src/main/java/econo/buddybridge/notification/entity/Notification.java
  src/main/java/econo/buddybridge/notification/exception/NotificationAccessDeniedException.java
  src/main/java/econo/buddybridge/notification/exception/NotificationNotFoundException.java
  src/main/java/econo/buddybridge/notification/repository/EmitterRepository.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepositoryCustom.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepositoryImpl.java
  src/main/java/econo/buddybridge/post/controller/PostController.java
  src/main/java/econo/buddybridge/post/controller/PostLikeController.java
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
  src/main/java/econo/buddybridge/post/dto/PostResDto.java
  src/main/java/econo/buddybridge/post/entity/AssistanceType.java
  src/main/java/econo/buddybridge/post/entity/District.java
  src/main/java/econo/buddybridge/post/entity/Post.java
  src/main/java/econo/buddybridge/post/entity/PostLike.java
  src/main/java/econo/buddybridge/post/entity/PostType.java
  src/main/java/econo/buddybridge/post/entity/Schedule.java
  src/main/java/econo/buddybridge/post/entity/ScheduleType.java
  src/main/java/econo/buddybridge/post/exception/PostErrorCode.java
  src/main/java/econo/buddybridge/post/exception/PostUnauthorizedAccessException.java
  src/main/java/econo/buddybridge/post/exception/PostUpdateNotAllowedException.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepositoryCustomImpl.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryCustom.java
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
  src/main/java/econo/buddybridge/post/service/PostLikeService.java
  src/main/java/econo/buddybridge/post/service/PostService.java
  src/main/java/econo/buddybridge/utils/session/SessionUtils.java
  src/main/java/econo/buddybridge/websocket/StompConfig.java
  src/main/java/econo/buddybridge/websocket/StompEventListener.java
Labels: enhancement
