Repository JNU-econovation/BuddyBridge_BE, pull requests merged in 2025-01, with the labels that each got.

#248 [CHORE] CORS 설정 PATCH 추가
  src/main/java/econo/buddybridge/config/WebConfig.java
Labels: bug

#252 [FIX] PostLike 엔티티에 대해 Cascade 적용
  src/main/java/econo/buddybridge/post/entity/Post.java
Labels: bug

#254 [FIX] 회원가입 시 Role.USER 기본값 적용
  src/main/java/econo/buddybridge/auth/dto/OAuthInfoResponse.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
Labels: bug

#257 [REFACTOR] 게시글 다중 삭제 로직 IN 쿼리 개선 및 연관된 댓글, 매칭 신고에 따른 soft delete 적용
  src/main/java/econo/buddybridge/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/econo/buddybridge/chat/chatmessage/repository/MessageReadStatusRepository.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/post/event/handler/PostDeleteEventHandler.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepository.java
  src/main/java/econo/buddybridge/post/repository/PostRepository.java
  src/main/java/econo/buddybridge/report/repository/CommentReportRepository.java
  src/main/java/econo/buddybridge/report/repository/MatchingReportRepository.java
  src/main/java/econo/buddybridge/report/repository/PostReportRepository.java
Labels: bug, enhancement

#263 [FEAT] 댓글 다중 삭제
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/comment/dto/CommentDeleteRequest.java
  src/main/java/econo/buddybridge/comment/entity/Comment.java
  src/main/java/econo/buddybridge/comment/event/CommentDeleteEvent.java
  src/main/java/econo/buddybridge/comment/event/handler/CommentDeleteEventHandler.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/report/repository/CommentReportRepository.java
Labels: enhancement

#261 [FEAT] 인증 폼 조회 기능 구현
  src/main/java/econo/buddybridge/certification/controller/AdminVolunteerCertificationController.java
  src/main/java/econo/buddybridge/certification/controller/VolunteerCertificationController.java
  src/main/java/econo/buddybridge/certification/dto/AdminCertificationAuthorDetailResponse.java
  src/main/java/econo/buddybridge/certification/dto/AdminCertificationDetailResponse.java
  src/main/java/econo/buddybridge/certification/dto/AdminCertificationPostDetailResponse.java
  src/main/java/econo/buddybridge/certification/dto/AdminVolunteerCertificationDetailResponse.java
  src/main/java/econo/buddybridge/certification/dto/VolunteerCertificationCustomPage.java
  src/main/java/econo/buddybridge/certification/dto/VolunteerCertificationListItem.java
  src/main/java/econo/buddybridge/certification/dto/VolunteerCertificationResponse.java
  src/main/java/econo/buddybridge/certification/repository/VolunteerCertificationCustomRepository.java
  src/main/java/econo/buddybridge/certification/repository/VolunteerCertificationCustomRepositoryImpl.java
  src/main/java/econo/buddybridge/certification/repository/VolunteerCertificationRepository.java
  src/main/java/econo/buddybridge/certification/service/VolunteerCertificationService.java
  src/main/java/econo/buddybridge/matching/entity/Matching.java
Labels: enhancement

#282 [FEAT] 관리자 인증 폼 봉사 시간 부여 기능 추가
  src/main/java/econo/buddybridge/certification/controller/AdminVolunteerCertificationController.java
  src/main/java/econo/buddybridge/certification/dto/AdminCertificationDetailResponse.java
  src/main/java/econo/buddybridge/certification/dto/VolunteerCertificationListItem.java
  src/main/java/econo/buddybridge/certification/entity/VolunteerCertification.java
  src/main/java/econo/buddybridge/certification/repository/VolunteerCertificationCustomRepositoryImpl.java
  src/main/java/econo/buddybridge/certification/service/VolunteerCertificationService.java
Labels: enhancement

#286 [REFACTOR] 댓글 조회 Order 파라미터 ValueEnum으로 검증
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/common/dto/PageOrder.java
  src/main/java/econo/buddybridge/common/exception/CommonErrorCode.java
  src/main/java/econo/buddybridge/common/exception/PageOrderInvalidTypeException.java
  src/main/java/econo/buddybridge/common/validation/EnumTypeValue.java
Labels: enhancement

#288 [FIX] 마이페이지 내가 쓴글 매칭 상태 변경을 위한 matchingId 필드 추가
  src/main/java/econo/buddybridge/matching/repository/MatchingRepositoryCustomImpl.java
  src/main/java/econo/buddybridge/post/dto/CompletedVolunteerPostDto.java
Labels: bug

#291 [FIX] Soft Delete 된 게시글에 대해 댓글과 매칭도 Soft Delete
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
  src/main/java/econo/buddybridge/post/event/handler/PostDeleteEventHandler.java
Labels: bug

#294 [FEAT] 신고 사유 500자 제한
  src/main/java/econo/buddybridge/report/dto/ReportRequest.java
  src/main/java/econo/buddybridge/report/entity/Report.java
Labels: enhancement

#296 [REFACTOR] 마이페이지 댓글 목록에서 게시글 상태 필드 제거
  src/main/java/econo/buddybridge/comment/dto/MyPageCommentResDto.java
  src/main/java/econo/buddybridge/comment/repository/CommentRepositoryImpl.java
Labels: enhancement

#300 [REFACTOR] 페이지네이션 API 페이지번호 0번부터 시작하도록 수정
  src/main/java/econo/buddybridge/certification/service/VolunteerCertificationService.java
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/post/service/PostService.java
Labels: enhancement

#298 [FEAT] 봉사 인증 요청 보낸지 24시간이 지났는지 판단하는 필드 채팅방 응답에 추가
  src/main/java/econo/buddybridge/chat/chatmessage/dto/ChatMessageCustomPage.java
  src/main/java/econo/buddybridge/chat/chatmessage/service/ChatMessageService.java
  src/main/java/econo/buddybridge/matching/entity/CertificationTracking.java
  src/main/java/econo/buddybridge/matching/entity/Matching.java
Labels: enhancement

#307 [FEAT] 신고된 댓글 상세 내용 조회 시 게시글 정보도 함께 반환
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/report/controller/AdminReportController.java
  src/main/java/econo/buddybridge/report/dto/ReportedCommentWithPostResponse.java
  src/main/java/econo/buddybridge/report/service/CommentReportService.java
Labels: enhancement

#321 [REFACTOR] 요청 본문 Validation 에러 응답을 error 필드에 담도록 변경
  src/main/java/econo/buddybridge/comment/controller/CommentController.java
  src/main/java/econo/buddybridge/common/exception/GlobalExceptionHandler.java
  src/main/java/econo/buddybridge/matching/dto/MatchingUpdateDto.java
  src/main/java/econo/buddybridge/post/dto/PostReqDto.java
  src/main/java/econo/buddybridge/post/dto/PostUpdateReqDto.java
  src/main/java/econo/buddybridge/post/entity/Post.java
  src/main/java/econo/buddybridge/post/entity/ScheduleType.java
  src/main/java/econo/buddybridge/post/exception/PostErrorCode.java
  src/main/java/econo/buddybridge/post/exception/ScheduleTypeInvalidException.java
  src/main/java/econo/buddybridge/post/mapper/PostMapper.java
  src/main/java/econo/buddybridge/report/dto/ReportRequest.java
  src/main/java/econo/buddybridge/utils/api/ApiResponseGenerator.java
Labels: enhancement

#323 [FEAT] 관리자 API - 사용자 목록 조회
  build.gradle
  src/main/java/econo/buddybridge/member/controller/AdminMemberController.java
  src/main/java/econo/buddybridge/member/dto/MemberCustomPage.java
  src/main/java/econo/buddybridge/member/dto/MemberListItem.java
  src/main/java/econo/buddybridge/member/repository/MemberRepository.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryCustom.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryImpl.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
  src/main/java/econo/buddybridge/report/controller/AdminReportController.java
  src/main/resources/application.yml
  src/test/java/econo/buddybridge/member/service/MemberServiceTest.java
Labels: enhancement

#325 [FEAT] 관리자 API - 사용자 다중 삭제
  src/main/java/econo/buddybridge/comment/repository/CommentRepository.java
  src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
  src/main/java/econo/buddybridge/member/controller/AdminMemberController.java
  src/main/java/econo/buddybridge/member/dto/MemberDeleteRequest.java
  src/main/java/econo/buddybridge/member/event/MemberDeleteEvent.java
  src/main/java/econo/buddybridge/member/event/handler/MemberDeleteEventHandler.java
  src/main/java/econo/buddybridge/member/repository/MemberRepository.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryImpl.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
  src/main/java/econo/buddybridge/notification/repository/NotificationRepository.java
  src/main/java/econo/buddybridge/notification/service/EmitterService.java
  src/main/java/econo/buddybridge/post/repository/PostLikeRepository.java
  src/main/java/econo/buddybridge/post/repository/PostRepository.java
  src/main/java/econo/buddybridge/report/repository/CommentReportRepository.java
  src/main/java/econo/buddybridge/report/repository/ReportRepository.java
Labels: enhancement

#326 [FEAT] 신고 대상자를 관리 할 블랙리스트 구현 및 신고 목록 반환 값 변경
  src/main/java/econo/buddybridge/blacklist/controller/BlackListController.java
  src/main/java/econo/buddybridge/blacklist/dto/BlackListRequest.java
  src/main/java/econo/buddybridge/blacklist/entity/BlackList.java
  src/main/java/econo/buddybridge/blacklist/exception/BlackListAlreadyExistsException.java
  src/main/java/econo/buddybridge/blacklist/exception/BlackListErrorCode.java
  src/main/java/econo/buddybridge/blacklist/exception/BlackListNotFoundException.java
  src/main/java/econo/buddybridge/blacklist/repository/BlackListRepository.java
  src/main/java/econo/buddybridge/blacklist/service/BlackListService.java
  src/main/java/econo/buddybridge/certification/dto/VolunteerCertificationListItem.java
  src/main/java/econo/buddybridge/certification/repository/VolunteerCertificationCustomRepositoryImpl.java
  src/main/java/econo/buddybridge/member/dto/MemberListItem.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryImpl.java
  src/main/java/econo/buddybridge/report/dto/ReportListItem.java
  src/main/java/econo/buddybridge/report/dto/ReportWithBlackListInfo.java
  src/main/java/econo/buddybridge/report/mapper/ReportMapper.java
  src/main/java/econo/buddybridge/report/service/ReportService.java
Labels: enhancement

#330 [REFACTOR] 게시글 필터링시 추가된 매칭 유형 고려
  src/main/java/econo/buddybridge/post/repository/PostRepositoryImpl.java
Labels: bug, enhancement

#332 [REFACTOR] WithDeletedContent 이름 변경 및 Pointcut 범위를 제한하는 어노테이션 적용
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/common/persistence/filter/annotation/SoftDeletableService.java
  src/main/java/econo/buddybridge/common/persistence/filter/aspect/SoftDeleteFilterAspect.java
  src/main/java/econo/buddybridge/matching/service/MatchingRoomService.java
  src/main/java/econo/buddybridge/matching/service/MatchingService.java
  src/main/java/econo/buddybridge/post/service/PostService.java
Labels: enhancement

#338 [FEAT] 신고 정보 조회에 신고자 및 피신고자 ID 반환
  src/main/java/econo/buddybridge/comment/service/CommentService.java
  src/main/java/econo/buddybridge/member/dto/MemberResDto.java
  src/main/java/econo/buddybridge/post/event/handler/PostDeleteEventHandler.java
  src/main/java/econo/buddybridge/report/dto/CommentReportDetailResponse.java
  src/main/java/econo/buddybridge/report/dto/MatchingReportDetailResponse.java
  src/main/java/econo/buddybridge/report/dto/PostReportDetailResponse.java
  src/main/java/econo/buddybridge/report/dto/ReportDetailResponse.java
  src/main/java/econo/buddybridge/report/dto/ReportListItem.java
  src/main/java/econo/buddybridge/report/mapper/ReportMapper.java
Labels: enhancement

#334 [FEAT] 블랙리스트 접근 제어 기능 추가
  src/main/java/econo/buddybridge/auth/service/AuthService.java
  src/main/java/econo/buddybridge/auth/service/OAuthLoginService.java
  src/main/java/econo/buddybridge/blacklist/exception/AdminCannotBeBlackListedException.java
  src/main/java/econo/buddybridge/blacklist/exception/BlackListErrorCode.java
  src/main/java/econo/buddybridge/blacklist/exception/BlackListRequestForbidden.java
  src/main/java/econo/buddybridge/blacklist/repository/BlackListRepository.java
  src/main/java/econo/buddybridge/blacklist/service/BlackListService.java
  src/main/java/econo/buddybridge/config/JwtInterceptor.java
  src/main/java/econo/buddybridge/member/entity/Member.java
Labels: enhancement

#346 [FEAT] 관리자 API - 사용자 목록에서 이름 검색
  src/main/java/econo/buddybridge/member/controller/AdminMemberController.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryCustom.java
  src/main/java/econo/buddybridge/member/repository/MemberRepositoryImpl.java
  src/main/java/econo/buddybridge/member/service/MemberService.java
  src/test/java/econo/buddybridge/member/service/MemberServiceTest.java
Labels: enhancement

#348 [FEAT] 설문조사 API
  build.gradle
  src/main/java/econo/buddybridge/common/persistence/MongoBaseEntity.java
  src/main/java/econo/buddybridge/survey/controller/SurveyController.java
  src/main/java/econo/buddybridge/survey/entity/MongoSurvey.java
  src/main/java/econo/buddybridge/survey/repository/SurveyRepository.java
  src/main/java/econo/buddybridge/survey/service/SurveyService.java
  src/main/resources/application.yml
  src/test/java/econo/buddybridge/survey/controller/SurveyControllerTest.java
  src/test/java/econo/buddybridge/survey/repository/SurveyRepositoryTest.java
Labels: enhancement

#350 [FEAT] Report 생성/삭제 시 신고 횟수에 따른 자동 블랙리스트 등록/해제 기능
  src/main/java/econo/buddybridge/report/event/ReportCreatedEvent.java
  src/main/java/econo/buddybridge/report/event/ReportDeletedEvent.java
  src/main/java/econo/buddybridge/report/event/handler/ReportCreatedEventHandler.java
  src/main/java/econo/buddybridge/report/event/handler/ReportDeletedEventHandler.java
  src/main/java/econo/buddybridge/report/repository/ReportRepositoryCustom.java
  src/main/java/econo/buddybridge/report/repository/ReportRepositoryImpl.java
  src/main/java/econo/buddybridge/report/service/CommentReportService.java
  src/main/java/econo/buddybridge/report/service/MatchingReportService.java
  src/main/java/econo/buddybridge/report/service/PostReportService.java
  src/main/java/econo/buddybridge/report/service/ReportService.java
Labels: enhancement

#356 [FEAT] 모집완료된 게시글에 댓글 작성 불가
  src/main/java/econo/buddybridge/chat/chatmessage/service/ChatMessageService.java
  src/main/java/econo/buddybridge/comment/exception/CommentErrorCode.java
  src/main/java/econo/buddybridge/comment/exception/CommentNotAllowedFinishedPostException.java
  src/main/java/econo/buddybridge/post/entity/Post.java
  src/main/java/econo/buddybridge/report/entity/ReportType.java
  src/test/java/econo/buddybridge/comment/service/CommentServiceTest.java
Labels: enhancement
